# Introduction


Happiness has been proven to be physically beneficial to the human body. A happier person has a lower risk for cardiovascular disease, has lower blood pressure, has a reduced amount of stress, gets better sleep, and generally lives longer than the average person.^[Referenced [Northwestern Medicine](https://www.nm.org/healthbeat/healthy-tips/how-happiness-impacts-health#:~:text=Protecting%20your%20health%3A%20Happiness%20lowers,regular%20exercise%20and%20reduces%20stress)] 

Although there isn’t a perfect formula to attain happiness, there are general trends that one could follow to have a pretty decent chance at increasing one’s happiness. A medically-reviewed paper from *PsychCentral* says that being driven, achieving long-term goals, and having meaningful relationships usually lead to a significant improvement on a person’s happiness.^[Referenced [PsychCentral](https://psychcentral.com/lib/15-ways-to-increase-your-happiness#1)] 

According to Edward Diener, a Senior Scientist who belongs to the *Gallup Organization*, the scientific term for happiness and general life satisfaction is subjective well-being.^[Referenced [Noba](https://nobaproject.com/modules/happiness-the-science-of-subjective-well-being#:~:text=Subjective%20well%2Dbeing%20(SWB),with%20other%20types%20of%20measures)] This is when people think that their life is going well compared to how bad it could be. To Diener, there are internal and external causes for influences a person’s happiness. The internal factors stem from a person’s inborn temperament, personality, and other psychological aspects. The external factors, however, point toward whether a person has sufficient financial resources or not. We will be exploring in detail the external influences through statistical point of view. In this article, we pull data from the *World Happiness Report* as the basis for our analysis when looking at national levels of happiness.^[Referenced [Kaggle](https://www.kaggle.com/unsdsn/world-happiness)]  

The research question we aim to answer is, “What external influences affect happiness and by how much?” Although we can’t give a concrete answer on the pursuit of happiness, we can take a step towards the right direction using statistics.
